### ISSUE TITLE
개발자님 수고 많으십니다. 에러 좀 확인 부탁드립니다.

### ISSUE THREAD

**Issue by yuyujava** [unvsDev/Flamingo#2]
플라밍고 꾸준하게 잘 쓰고 있는데 이번엔 안되는 기간이 길어져서 글 남겨봅니다..ㅠ
에러는 첨부 그림과 같습니다.
![photo_2022-07-13_08-35-13](https://user-images.githubusercontent.com/109186093/178615986-e8ce7c73-e05a-4027-8df7-ee1dca1a4cac.jpg)

**Comment by root-devvoo** [comment]
맞아요 ㅠ 해결 부탁드립니다

**Comment by bagng** [comment]
Flamingo.js 에서 260줄을 다음과 같이 수정하시면 됩니다.
        let productLinkEle = ele.querySelector('.product-element-top .product-image-link')
===>
        let productLinkEle = ele.querySelector('.product-element-top')

그리고 262줄을 다음과 같이 수정하시면 됩니다.
        let productInfoEle = ele.querySelector('.product-element-bottom > span')
===>
        let productInfoEle = ele.querySelector('.product-element-bottom')

**Comment by yuyujava** [comment]
> Flamingo.js 에서 260줄을 다음과 같이 수정하시면 됩니다. let productLinkEle = ele.querySelector('.product-element-top .product-image-link') ===> let productLinkEle = ele.querySelector('.product-element-top')
> 
> 그리고 262줄을 다음과 같이 수정하시면 됩니다. let productInfoEle = ele.querySelector('.product-element-bottom > span') ===> let productInfoEle = ele.querySelector('.product-element-bottom')

감사합니다. 약 두달정도 화면 안바꾸고 그대로 있었는데 말씀하신대로 수정하니 드디어 나오네요. 정말 감사합니다!

**Comment by root-devvoo** [comment]
감사합니다 :)
